# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: d
script: bash build_script.bash
sudo: required

env:
  global:
    - REPO="show0k/travis-test"
    - CI_HOME=`pwd`/$REPO

notifications:
   email:theo.segonds+travisspam@gmail.com

