#!/usr/bin/env bash
# OctoPi generation script
# This script takes a Raspbian image and adds to it octoprint and verions addons
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3

source $OCTOPI_SCRIPT_PATH/common.sh

function execute_chroot_script() {
  #move OctoPi filesystem files
  cp -vr --preserve=mode,timestamps $1/filesystem .

  #black magic of qemu-arm-static
  cp `which qemu-arm-static` usr/bin
  
  cp $2 chroot_script
  chmod 755 chroot_script
  cp $OCTOPI_SCRIPT_PATH/common.sh common.sh
  chmod 755 common.sh
  
  chroot . usr/bin/qemu-arm-static /bin/bash /chroot_script
  
  #cleanup
  rm chroot_script
  rm -rfv filesystem
}

mkdir -p $OCTOPI_WORKSPACE
mkdir -p $OCTOPI_MOUNT_PATH

install_fail_on_error_trap $OCTOPI_MOUNT_PATH
unmount_image $OCTOPI_MOUNT_PATH || true

pushd $OCTOPI_WORKSPACE
  if [ -e *.img ]; then  
    rm *.img
  fi
  # "${OCTOPI_ZIP_IMG%.*}.img"
  export OCTOPI_IMG_PATH=$PWD/Poppy_rpi.img
  unzip -p $OCTOPI_ZIP_IMG | pv > $OCTOPI_IMG_PATH
  #OCTOPI_IMG_PATH=`ls | grep .img`

  # mount root and boot partition
  mount_image $OCTOPI_IMG_PATH $OCTOPI_MOUNT_PATH
  mount --bind /etc/resolv.conf $OCTOPI_MOUNT_PATH/etc/resolv.conf

  #Edit pi filesystem
  pushd $OCTOPI_MOUNT_PATH

    #make QEMU boot (remember to return)
    fixLd
    #sed -i 's@include /etc/ld.so.conf.d/\*.conf@\#include /etc/ld.so.conf.d/\*.conf@' etc/ld.so.conf
 
    # execute the base chroot script
    execute_chroot_script $OCTOPI_SCRIPT_PATH $OCTOPI_CHROOT_SCRIPT_PATH
        
    restoreLd
  popd
  
  # unmount first boot, then root partition
  unmount_image $OCTOPI_MOUNT_PATH
  chmod 777 $OCTOPI_IMG_PATH
popd

